Add latest wine-staging support

diff --git a/templates/vdi/desktop/Dockerfile b/templates/vdi/desktop/Dockerfile
--- a/templates/vdi/desktop/Dockerfile
+++ b/templates/vdi/desktop/Dockerfile
@@ -265,42 +265,10 @@ RUN true \
     && rm -rf "${DEEPSTREAM_SAMPLE_HOME}" \
     && rm -f "${DEEPSTREAM_SDK_FILE}"
 
-# Install WINE
-ARG WINE_REPO="https://github.com/Kron4ek/Wine-Builds/releases/download"
-RUN true \
-    # Get the latest version
-    && WINE_ARCH="amd64" \
-    && WINE_VERSION="8.1" \
-    # Install dependencies
-    && dnf install -y wine \
-    && dnf remove -y --noautoremove "wine*" \
-    && dnf install -y \
-    winetricks \
-    # Download
-    && WINE_HOME="/opt/wine" \
-    && WINE_OBJ_FILE="/opt/wine.tar.xz" \
-    && wget -O "${WINE_OBJ_FILE}" "${WINE_REPO}/${WINE_VERSION}/wine-${WINE_VERSION}-staging-tkg-${WINE_ARCH}.tar.xz" \
-    # Decompress the downloaded file
-    && mkdir -p "${WINE_HOME}" \
-    && tar -x -C "${WINE_HOME}" -f "${WINE_OBJ_FILE}" \
-    # Environment Variables Configuration
-    && echo '# WINE binary path registration' >/etc/profile.d/path-wine-bin.sh \
-    && echo '# WINE library path registration' >/etc/ld.so.conf.d/900-wine.conf \
-    && for wine_home in ${WINE_HOME}/wine\-*; do true \
-    && echo "export PATH=\${PATH}:${wine_home}/bin" >>/etc/profile.d/path-wine-bin.sh \
-    && echo "${wine_home}/lib" >>/etc/ld.so.conf.d/900-wine.conf \
-    ; done \
-    && ldconfig \
-    # Cleanup
-    && dnf clean all \
-    && rm -rf /var/cache /var/log/dnf* /var/log/yum.* \
-    && rm -rf "${WINE_OBJ_FILE}"
-
-# Install utilities
+# Install utility
 RUN ARCH_WIN32='i686' \
     && dnf install -y \
     # Games (Lutris)
-    gamemode \
     "gnutls.${ARCH_WIN32}" \
     "mesa-dri-drivers.${ARCH_WIN32}" \
     "mesa-libEGL.${ARCH_WIN32}" \
@@ -314,9 +282,41 @@ RUN ARCH_WIN32='i686' \
     python3-requests \
     "vulkan-loader.${ARCH_WIN32}" \
     webkit2gtk3 \
+    wine \
+    winetricks \
     # Cleanup
     && dnf clean all \
     && rm -rf /var/cache /var/log/dnf* /var/log/yum.*
+
+# Install utility - WINE staging
+ARG WINE_REPO="https://github.com/Kron4ek/Wine-Builds/releases/download"
+RUN true \
+    # Get the latest version
+    ## ARCH
+    && case "$(uname -m)" in \
+    'i386') \
+    WINE_ARCH='x86' \
+    ;; \
+    'x86_64') \
+    WINE_ARCH='amd64' \
+    ;; \
+    *) \
+    echo "Unsupported WINE Architechure: '$(uname -m)'" \
+    exit 1 \
+    ;; \
+    esac \
+    && WINE_VERSION="8.1" \
+    # Download
+    && WINE_OBJ_NAME="wine-${WINE_VERSION}-staging-tkg-${WINE_ARCH}" \
+    && WINE_OBJ_FILENAME="${WINE_OBJ_NAME}.tar.xz" \
+    && WINE_OBJ_FILE="${WINE_OBJ_FILENAME}" \
+    && WINE_TMP="/opt/${WINE_OBJ_NAME}" \
+    && wget -O "${WINE_OBJ_FILE}" "${WINE_REPO}/${WINE_VERSION}/${WINE_OBJ_FILENAME}" \
+    # Decompress the downloaded file
+    && tar -x -C "$(dirname "${WINE_TMP}")" -f "${WINE_OBJ_FILE}" \
+    && tar -cf - -C "${WINE_TMP}" . | tar -xf - -C '/usr' \
+    # Cleanup
+    && rm -rf "${WINE_OBJ_FILE}" "${WINE_TMP}"
 
 # Install utilities - Games - Lutris
 ARG LUTRIS_REPO="https://lutris.net/releases"
@@ -348,9 +348,7 @@ RUN true \
 # Install utilities - Custom
 ARG ADDONS_HOME="/opt/netai-cloud/vdi/desktop"
 ADD ./addons "${ADDONS_HOME}"
-RUN for file in ${ADDONS_HOME}/bin/*; do true \
-    && chmod a+x "${file}" \
-    ; done \
+RUN chmod -R a+x "${ADDONS_HOME}/bin" \
     && for file in ${ADDONS_HOME}/share/applications/*.desktop; do true \
     && ln -s "${file}" "/usr/share/applications/$(basename "${file}")" \
     ; done \
