feat(vine): add rootless docker support

diff --git a/templates/vine/desktop/Dockerfile.ubuntu-pytorch b/templates/vine/desktop/Dockerfile.ubuntu-pytorch
--- a/templates/vine/desktop/Dockerfile.ubuntu-pytorch
+++ b/templates/vine/desktop/Dockerfile.ubuntu-pytorch
@@ -23,6 +23,8 @@ ARG USER_SHELL
 ARG USER_SUDO
 ARG USER_UID
 
+ENV USER_SHELL="${USER_SHELL}"
+
 # Package Manager Configuration
 ARG DEBIAN_FRONTEND='noninteractive'
 
@@ -39,6 +41,11 @@ CMD [ "/usr/bin/systemctl", "init", "vine-desktop.service", "--system" ]
 ## home.user
 VOLUME [ "/home/${USER_NAME}" ]
 
+# Configure package manager
+RUN dst='/etc/apt/apt.conf.d/docker-minimal' \
+    && echo 'APT::Install-Recommends "false";' >"${dst}" \
+    && echo 'APT::Install-Suggests "false";' >>"${dst}"
+
 # Add core repositories
 ADD ./apt/keyrings/* /etc/apt/keyrings/
 ADD ./apt/sources.list.d/*.list /etc/apt/sources.list.d/
@@ -51,6 +58,7 @@ RUN true \
     # Get OS informations
     && . /etc/os-release \
     && export ARCH="$(uname -m)" \
+    && export VERSION_CODENAME="${VERSION_CODENAME}" \
     && export VERSION_ID_MAJOR="${VERSION_ID%\.[0-9]*}" \
     && export VERSION_ID_MINOR="${VERSION_ID#[0-9]*\.}" \
     # Update keyrings
@@ -63,45 +71,31 @@ RUN true \
     && apt-get clean all \
     && rm -rf /var/lib/apt/lists/*
 
-# Install init program
-ADD ./systemd/vine-desktop.service "/usr/lib/systemd/system/vine-desktop.service"
-ARG INIT_JOURNALCTL_URL="https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/master/files/docker/journalctl3.py"
-ARG INIT_SYSTEMCTL_URL="https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/master/files/docker/systemctl3.py"
-RUN apt-get update && apt-get install -y \
-    curl \
-    procps \
-    python3 \
-    && curl -s "${INIT_JOURNALCTL_URL}" -o '/usr/bin/journalctl' \
-    && curl -s "${INIT_SYSTEMCTL_URL}" -o '/usr/bin/systemctl' \
-    && rm -rf '/etc/systemd/system/multi-user.target.wants' \
-    && mkdir -p '/etc/systemd/system/multi-user.target.wants' \
-    && ln -sf \
-    '/usr/lib/systemd/system/vine-desktop.service' \
-    '/etc/systemd/system/multi-user.target.wants/vine-desktop.service' \
-    && mkdir -p '/opt/scripts' \
-    && echo 'sleep infinity' >'/opt/scripts/entrypoint-desktop.sh' \
-    && chmod a+x /opt/scripts/* \
-    # Cleanup
-    && apt-get clean all \
-    && rm -rf /var/lib/apt/lists/*
-
 # Install core dependencies
 RUN apt-get update && apt-get install -y \
     apt-transport-https \
     curl \
+    dbus-user-session \
+    fancontrol \
     gpg \
-    libgles2-mesa-dev \
-    libglfw3-dev \
+    i2c-tools \
     libhwloc-dev \
     libldacbt-abr2 \
     libldacbt-enc2 \
+    libosmesa6 \
+    libpipewire-0.3-common \
     libspa-0.2-bluetooth \
-    mesa-vulkan-drivers \
+    libvulkan1 \
+    lm-sensors \
+    mesa-utils \
+    pciutils \
     pipewire \
     pipewire-audio-client-libraries \
     pipewire-media-session- \
     pipewire-pulse \
     pulseaudio-module-bluetooth- \
+    read-edid \
+    vulkan-icd \
     wireplumber \
     wmctrl \
     x11-utils \
@@ -123,19 +117,25 @@ RUN apt-get update && apt-get install -y \
 # Install development environment dependencies
 RUN apt-get update && apt-get install -y \
     crun \
+    docker-ce \
+    docker-ce-cli \
+    docker-ce-rootless-extras \
+    docker-compose-plugin \
     fuse-overlayfs \
     git \
+    iptables \
     kubectl \
     nano \
     nodejs \
     nvidia-container-toolkit-base \
     openssh-client \
     pciutils \
-    podman-docker \
     python3 \
     python3-pip \
     screen \
+    slirp4netns \
     sudo \
+    uidmap \
     "${USER_SHELL}" \
     vim \
     wget \
@@ -144,13 +144,12 @@ RUN apt-get update && apt-get install -y \
     && test "x${USER_SUDO}" = "xtrue" \
     && echo "${USER_NAME} ALL=(ALL) NOPASSWD: ALL" >/etc/sudoers.d/10-wheel \
     && chmod 440 /etc/sudoers.d/10-wheel \
-    # Docker (Podman) Configuration
+    # Docker Configuration
     && chmod u+s /usr/bin/newuidmap /usr/bin/newgidmap \
-    && systemctl enable podman \
-    && touch /etc/containers/nodocker \
-    # Podman-Compose Configuration
-    && pip3 install podman-compose \
+    && sed -i 's/systemctl --user show-environment/true/g' /usr/bin/dockerd-rootless-setuptool.sh \
+    && systemctl disable docker.service docker.socket \
     ## chmod containers.conf and adjust storage.conf to enable Fuse storage.
+    && mkdir -p /etc/containers/ \
     && echo '[storage]' >/etc/containers/storage.conf \
     && echo 'driver = "overlay"' >>/etc/containers/storage.conf \
     && echo 'runroot = "/run/containers/storage"' >>/etc/containers/storage.conf \
@@ -185,6 +184,8 @@ RUN apt-get update && apt-get install -y \
     && echo '/usr/local/lib' >>/etc/ld.so.conf.d/100-path-local-lib.conf \
     && echo '/usr/local/lib64' >>/etc/ld.so.conf.d/100-path-local-lib.conf \
     && ldconfig \
+    # SystemD Configuration
+    && chmod u+x /usr/bin/systemctl \
     # Cleanup
     && apt-get clean all \
     && rm -rf /var/lib/apt/lists/*
@@ -218,6 +219,28 @@ RUN apt-get update && apt-get install -y \
     && apt-get clean all \
     && rm -rf /var/lib/apt/lists/*
 
+# Install init program
+ADD ./systemd/vine-desktop.service "/usr/lib/systemd/system/vine-desktop.service"
+ARG INIT_JOURNALCTL_URL="https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/master/files/docker/journalctl3.py"
+ARG INIT_SYSTEMCTL_URL="https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/master/files/docker/systemctl3.py"
+RUN apt-get update && apt-get install -y \
+    curl \
+    procps \
+    python3 \
+    && curl -s "${INIT_JOURNALCTL_URL}" -o '/usr/bin/journalctl' \
+    && curl -s "${INIT_SYSTEMCTL_URL}" -o '/usr/bin/systemctl' \
+    && rm -rf '/etc/systemd/system/multi-user.target.wants' \
+    && mkdir -p '/etc/systemd/system/multi-user.target.wants' \
+    && ln -sf \
+    '/usr/lib/systemd/system/vine-desktop.service' \
+    '/etc/systemd/system/multi-user.target.wants/vine-desktop.service' \
+    && mkdir -p '/opt/scripts' \
+    && echo 'sleep infinity' >'/opt/scripts/entrypoint-desktop.sh' \
+    && chmod a+x /opt/scripts/* \
+    # Cleanup
+    && apt-get clean all \
+    && rm -rf /var/lib/apt/lists/*
+
 # Install internet browsers
 RUN apt-get update && apt-get install -y \
     firefox \
@@ -225,6 +248,128 @@ RUN apt-get update && apt-get install -y \
     # Cleanup
     && apt-get clean all \
     && rm -rf /var/lib/apt/lists/*
+
+# Install AI dev dependencies
+ARG DEEPSTREAM_REFERENCES_REPO_URL="https://github.com/NVIDIA-AI-IOT/deepstream_reference_apps.git"
+ARG DEEPSTREAM_URL_DOWNLOAD="https://developer.download.nvidia.com/assets/Deepstream"
+ARG DEEPSTREAM_VERSION_MAJOR="6"
+ARG DEEPSTREAM_VERSION_MINOR="2"
+ARG DEEPSTREAM_VERSION_PATCH="0"
+ARG DEEPSTREAM_VERSION_URL="https://raw.githubusercontent.com/NVIDIA-AI-IOT/deepstream_dockers/main/common/version"
+RUN apt-get update && apt-get install -y \
+    gstreamer1.0-alsa \
+    gstreamer1.0-gl \
+    gstreamer1.0-gtk3 \
+    gstreamer1.0-libav \
+    gstreamer1.0-pipewire \
+    gstreamer1.0-plugins-bad \
+    gstreamer1.0-plugins-base \
+    gstreamer1.0-plugins-good \
+    gstreamer1.0-plugins-ugly \
+    gstreamer1.0-pulseaudio \
+    gstreamer1.0-qt5 \
+    gstreamer1.0-tools \
+    gstreamer1.0-vaapi \
+    gstreamer1.0-x \
+    libgstreamer1.0-dev \
+    libgstreamer-plugins-bad1.0-dev \
+    libgstreamer-plugins-base1.0-dev \
+    libgstrtspserver-1.0 \
+    libjansson4 \
+    libssl3 \
+    libssl-dev \
+    libyaml-cpp-dev \
+    # Get the latest version
+    && DEEPSTREAM_VERSION=$( \
+    curl -s "${DEEPSTREAM_VERSION_URL}" \
+    | grep -Po '^version\=\K[0-9\.]+$' \
+    ) \
+    # Parse the version information
+    && DEEPSTREAM_HOME="/opt/nvidia/deepstream/deepstream" \
+    && DEEPSTREAM_VERSION_MAJOR="${DEEPSTREAM_VERSION_MAJOR:-"$(echo "${DEEPSTREAM_VERSION}" | awk -F '.' '{print $1}')"}" \
+    && DEEPSTREAM_VERSION_MINOR="${DEEPSTREAM_VERSION_MINOR:-"$(echo "${DEEPSTREAM_VERSION}" | awk -F '.' '{print $2}')"}" \
+    && DEEPSTREAM_VERSION_PATCH="${DEEPSTREAM_VERSION_PATCH:-"$(echo "${DEEPSTREAM_VERSION}" | awk -F '.' '{print $3}')"}" \
+    && DEEPSTREAM_VERSION_RELEASE="${DEEPSTREAM_VERSION_MAJOR}.${DEEPSTREAM_VERSION_MINOR}" \
+    && DEEPSTREAM_VERSION_FULL="${DEEPSTREAM_VERSION_RELEASE}.${DEEPSTREAM_VERSION_PATCH}" \
+    # Download
+    && DEEPSTREAM_SDK_FILE="/opt/deepstream-sdk.tbz2" \
+    && wget -qO "${DEEPSTREAM_SDK_FILE}" "${DEEPSTREAM_URL_DOWNLOAD}/DeepStream_${DEEPSTREAM_VERSION_RELEASE}/deepstream_sdk_v${DEEPSTREAM_VERSION_FULL}_$(uname -m).tbz2" \
+    # Decompress the downloaded file
+    && tar -x -C '/' -f "${DEEPSTREAM_SDK_FILE}" \
+    # Install
+    && pushd "${DEEPSTREAM_HOME}" \
+    && sed -i 's/"rhel"/"rocky"/g' ./*.sh \
+    && ./install.sh && ldconfig \
+    && rm -f *.sh \
+    && popd \
+    # Download the latest configuration files
+    && DEEPSTREAM_MODELS_DIR="${DEEPSTREAM_HOME}/samples/configs/tao_pretrained_models" \
+    && DEEPSTREAM_SAMPLE_HOME="/opt/deepstream_reference_apps" \
+    && git clone "${DEEPSTREAM_REFERENCES_REPO_URL}" "${DEEPSTREAM_SAMPLE_HOME}" \
+    && pushd "${DEEPSTREAM_SAMPLE_HOME}/deepstream_app_tao_configs/" \
+    && cp -a * "${DEEPSTREAM_MODELS_DIR}" \
+    && popd \
+    # Download the models
+    && pushd "${DEEPSTREAM_MODELS_DIR}" \
+    && ./download_models.sh \
+    && popd \
+    # Change permissions for user-level modification
+    && chown -R "${USER_UID}:${USER_GID}" "${DEEPSTREAM_HOME}/samples" \
+    # Cleanup
+    && rm -rf "${DEEPSTREAM_SAMPLE_HOME}" \
+    && rm -f "${DEEPSTREAM_SDK_FILE}"
+
+# Install utility
+RUN apt-get update && apt-get install -y \
+    # Games (Lutris)
+    libegl1-mesa \
+    libglu1-mesa \
+    libnsl2 \
+    libunwind-dev \
+    libvulkan1 \
+    libwebkit2gtk-4.1 \
+    lutris \
+    python3-certifi \
+    python3-dbus \
+    python3-distro \
+    python3-lxml \
+    python3-pillow \
+    python3-requests \
+    python3-yaml \
+    wine \
+    # Cleanup
+    && apt-get clean all \
+    && rm -rf /var/lib/apt/lists/*
+
+# Install utility - WINE staging
+ARG WINE_REPO="https://github.com/Kron4ek/Wine-Builds/releases/download"
+RUN true \
+    # Get the latest version
+    ## ARCH
+    && case "$(uname -m)" in \
+    'i386') \
+    WINE_ARCH='x86' \
+    ;; \
+    'x86_64') \
+    WINE_ARCH='amd64' \
+    ;; \
+    *) \
+    echo "Unsupported WINE Architechure: '$(uname -m)'" \
+    exit 1 \
+    ;; \
+    esac \
+    && WINE_VERSION="9.2" \
+    # Download
+    && WINE_OBJ_NAME="wine-${WINE_VERSION}-staging-tkg-${WINE_ARCH}" \
+    && WINE_OBJ_FILENAME="${WINE_OBJ_NAME}.tar.xz" \
+    && WINE_OBJ_FILE="${WINE_OBJ_FILENAME}" \
+    && WINE_TMP="/opt/${WINE_OBJ_NAME}" \
+    && wget -qO "${WINE_OBJ_FILE}" "${WINE_REPO}/${WINE_VERSION}/${WINE_OBJ_FILENAME}" \
+    # Decompress the downloaded file
+    && tar -x -C "$(dirname "${WINE_TMP}")" -f "${WINE_OBJ_FILE}" \
+    && tar -cf - -C "${WINE_TMP}" . | tar -xf - -C '/usr' \
+    # Cleanup
+    && rm -rf "${WINE_OBJ_FILE}" "${WINE_TMP}"
 
 # Install utilities - Custom
 ARG ADDONS_HOME="/opt/openark/vdi/desktop"
@@ -261,7 +406,7 @@ RUN chmod 0555 /opt/scripts/*
 # Add a user
 RUN ldconfig \
     && groupadd -g "${USER_GID}" -o "${USER_NAME}" \
-    && useradd -u "${USER_UID}" -g "${USER_GID}" -G "audio,cdrom,input,pulse,render,video" \
+    && useradd -u "${USER_UID}" -g "${USER_GID}" -G "audio,cdrom,input,render,video" \
     -s "/bin/${USER_SHELL}" -m -o "${USER_NAME}" \
     && echo -e "${USER_UID}:2001:65535" > /etc/subuid \
     && echo -e "${USER_GID}:2001:65535" > /etc/subgid
